import express from 'express';

const app = express();
const PORT = Number(process.env.PORT || 10000);
const EDGE_BASE = process.env.EDGE_BASE || 'https://ducnpyybicybkkazaugo.supabase.co/functions/v1/tuconis-preventa';
const EDGE_PATH = '/functions/v1/tuconis-preventa';

app.get('/health', (_req,res)=>res.json({ok:true,service:'tuconis-render-proxy'}));

app.use(async (req,res) => {
  try {
    // Normalize accidental internal Supabase paths back to public app paths.
    let original = req.originalUrl || '/';
    if (original.startsWith(EDGE_PATH)) {
      original = original.slice(EDGE_PATH.length) || '/';
    }

    const suffix = original === '/' ? '' : original;
    const target = EDGE_BASE + suffix;
    const headers = new Headers();

    for (const [k,v] of Object.entries(req.headers)) {
      if (v == null) continue;
      const key = k.toLowerCase();
      if (['host','content-length','connection','accept-encoding'].includes(key)) continue;
      headers.set(k, Array.isArray(v) ? v.join(',') : String(v));
    }

    const init = { method:req.method, headers, redirect:'manual' };
    if (!['GET','HEAD'].includes(req.method)) {
      init.body = req;
      init.duplex = 'half';
    }

    const upstream = await fetch(target, init);
    res.status(upstream.status);

    let upstreamType = '';
    upstream.headers.forEach((value,key)=>{
      const lower = key.toLowerCase();
      if (lower === 'content-type') upstreamType = value;

      // Do not forward gateway/security headers that block the inline CSS generated by the app.
      if ([
        'content-length','content-encoding','transfer-encoding','connection','content-type',
        'content-security-policy','content-security-policy-report-only','x-content-type-options'
      ].includes(lower)) return;

      if (lower === 'location') {
        const publicBase = `${req.protocol}://${req.get('host')}`;
        value = value.replace(EDGE_BASE, publicBase);
        value = value.replace('https://ducnpyybicybkkazaugo.supabase.co/functions/v1/tuconis-preventa', publicBase);
        value = value.replace(EDGE_PATH, '');
      }
      res.setHeader(key,value);
    });

    const isHtml = original === '/' || original === '/admin' || upstreamType.includes('text/html');

    if (isHtml) {
      res.setHeader('Content-Type','text/html; charset=utf-8');
      // Explicit CSP that allows the current inline stylesheet and no framing.
      res.setHeader('Content-Security-Policy', "default-src 'self' https: data:; style-src 'self' 'unsafe-inline'; img-src 'self' https: data:; script-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'");

      let body = await upstream.text();
      const publicBase = `${req.protocol}://${req.get('host')}`;

      // Rewrite absolute/internal Supabase links and forms so navigation always stays on Render.
      body = body
        .replaceAll(EDGE_BASE, publicBase)
        .replaceAll('https://ducnpyybicybkkazaugo.supabase.co/functions/v1/tuconis-preventa', publicBase)
        .replaceAll(EDGE_PATH + '/admin', '/admin')
        .replaceAll(EDGE_PATH, '/');

      return res.send(body);
    }

    if (upstreamType) res.setHeader('Content-Type', upstreamType);
    const body = Buffer.from(await upstream.arrayBuffer());
    return res.end(body);
  } catch (err) {
    console.error(err);
    res.status(502).type('text/plain').send('No se pudo conectar con el backend de Tuconi\'s.');
  }
});

app.listen(PORT,'0.0.0.0',()=>console.log(`Tuconi's proxy listening on ${PORT}`));
