import{readFileSync,writeFileSync}from'node:fs';
let s=readFileSync(new URL('./proxy-v34.js',import.meta.url),'utf8');
const cartStart=s.indexOf('const cart=`');
const cartEnd=s.indexOf('`;const shell=',cartStart);
if(cartStart<0||cartEnd<0)throw new Error('cart template not found');
// v51: definitive product labels GRIS/BORDÓ/AZUL and new gray photo.
const cart=`const cart=\`<button class=cartbtn type=button data-cart-toggle>🛒 Carrito <span id=tcN>0</span></button><aside class=drawer id=tcD><b>Tu carrito</b><div id=tcItems></div><div id=tcPrice style="padding:12px 0;font-weight:900"></div><a class=btn href=/checkout>Ir al checkout →</a></aside><script>var TCK='tuconis-cart-v1',TCN={black:'GRIS',red:'BORDÓ',blue:'AZUL'};function tcGet(){try{return JSON.parse(localStorage.getItem(TCK)||'{}')}catch(e){return{}}}function tcSave(c){localStorage.setItem(TCK,JSON.stringify(c));tcRender()}function tcQty(){return Object.values(tcGet()).reduce(function(a,b){return a+Number(b||0)},0)}function tcPrice(n){return Math.floor(n/2)*50000+(n%2)*28000}function tcRender(){var c=tcGet(),n=tcQty(),el=document.getElementById('tcN');if(el)el.textContent=n;var x=document.getElementById('tcItems');if(x){var rows=Object.entries(c).filter(function(kv){return Number(kv[1])>0}).map(function(kv){var k=kv[0],v=kv[1];return '<div class="cartrow"><span>'+TCN[k]+'</span><span class="ctrl"><button type="button" data-cart-change="-1" data-model="'+k+'">−</button><b>'+v+'</b><button type="button" data-cart-change="1" data-model="'+k+'">+</button></span></div>'}).join('');x.innerHTML=rows||'<p>Tu carrito está vacío.</p>'}var p=document.getElementById('tcPrice');if(p)p.textContent=n?'Total estimado por transferencia: $'+tcPrice(n).toLocaleString('es-AR'):''}function tcChg(k,d){var c=tcGet();c[k]=Math.max(0,Number(c[k]||0)+Number(d));tcSave(c);if(typeof syncCheckout==='function')syncCheckout()}function tcAdd(k,n){n=n||1;var c=tcGet();c[k]=Number(c[k]||0)+n;tcSave(c);var d=document.getElementById('tcD');if(d)d.classList.add('open')}function tcToggle(){var d=document.getElementById('tcD');if(d)d.classList.toggle('open')}document.addEventListener('DOMContentLoaded',function(){tcRender();document.addEventListener('click',function(e){var add=e.target.closest('[data-add-cart]');if(add){e.preventDefault();tcAdd(add.getAttribute('data-model'),1);return}var ch=e.target.closest('[data-cart-change]');if(ch){e.preventDefault();tcChg(ch.getAttribute('data-model'),Number(ch.getAttribute('data-cart-change')));return}var tog=e.target.closest('[data-cart-toggle]');if(tog){e.preventDefault();tcToggle()}})});</script>\``;
s=s.slice(0,cartStart)+cart+s.slice(cartEnd+1);
// Definitive catalog labels and gray-cap asset.
s=s.replace("p2:['WhatsApp Image 2026-09-11 at 12.36.16 (1).jpeg','image/jpeg']","p2:['WhatsApp Image 2026-09-11 at 12.36.16 (2).jpeg','image/jpeg']");
s=s.replace("const pics={black:['GRIS / NEGRA','p2'],red:['ROJA / BORDÓ','p1'],blue:['AZUL','p5']}","const pics={black:['GRIS','p2'],red:['BORDÓ','p1'],blue:['AZUL','p5']}");
s=s.replace(".adminlegacy{display:none!important}",".adminlegacy{display:none!important}.socialfooter{position:relative;z-index:2;text-align:center;padding:34px 12px 26px;font-family:Arial,sans-serif;font-size:14px;font-weight:600;letter-spacing:.4px}.socialfooter a{color:#eee8df;text-decoration:none;margin:0 12px;border-bottom:1px solid #ef3030;padding-bottom:3px}.socialfooter a:hover{color:#ef3030}.orderopaque{position:relative;z-index:3}.orderopaque .c{position:relative!important;z-index:5!important;background:#191b1c!important;opacity:1!important;box-shadow:0 14px 40px #0008}.orderopaque .x{position:relative!important;z-index:6!important;background:#743247!important;opacity:1!important}@media(max-width:700px){.wm{position:absolute!important;inset:-20vh -65vw!important;min-height:180vh!important;background-size:180px auto!important;transform:rotate(-14deg)!important;filter:contrast(1.55) brightness(1.55)!important;opacity:.82!important}table{min-width:760px}main.admin{width:calc(100% - 16px)!important}.admin .card{overflow-x:auto}.admin select,.admin button{min-height:44px}}");
s=s.replace("${cards()}</main>`))});app.get('/promo'","${cards()}</main><footer class=socialfooter><a href=\"https://www.instagram.com/tuconis/\" target=\"_blank\" rel=\"noopener\">Instagram · @tuconis</a><a href=\"https://www.youtube.com/@Tuconis\" target=\"_blank\" rel=\"noopener\">YouTube · @Tuconis</a></footer>`))});app.get('/promo'");
s=s.replaceAll("<button class=btn onclick=\"tcAdd('${id}')\">Agregar al carrito</button>","<button type=button class=btn data-add-cart data-model=\"${id}\">Agregar al carrito</button>");
s=s.replace("<div class=price>1 GORRA · $30.000</div>","<a class=price href=/checkout>1 GORRA<br><small>TRANSFERENCIA · $28.000</small><br><small>MERCADO PAGO (DÉBITO / CRÉDITO) · $30.500</small><br><small>Ir al checkout →</small></a>");
s=s.replace("2 GORRAS · $50.000<br><small>Elegí cualquier combinación →</small>","PROMOCIÓN · 2 GORRAS · $50.000<br><small>SOLO TRANSFERENCIA · hasta agotar 5 pares<br>Elegí cualquier combinación →</small>");
s=s.replace("Podés combinar colores o elegir dos iguales. La promo se suma a lo que ya tengas en el carrito.","Podés combinar colores o elegir dos iguales. Promoción exclusiva por transferencia directa. No disponible con débito ni crédito.");
s=s.replace("<div class=pay><b>Forma de pago</b>","<div class=pay><b>Forma de pago</b><p><small>Transferencia: $28.000 por gorra; PROMOCIÓN 2 × $50.000 mientras haya cupo. Mercado Pago (débito/crédito): $30.500 por gorra, sin promoción.</small></p>");
s=s.replace("Mientras haya cupo promocional, cada par se cobra $50.000 y las unidades restantes $30.000 c/u. El servidor confirma el precio final al crear el pedido.","Por transferencia, mientras haya cupo promocional, cada par se cobra $50.000 y las unidades restantes $28.000 c/u. Con Mercado Pago cada gorra cuesta $30.500 y la promoción no se aplica. El servidor confirma el total final.");
// Supabase sets Path=/ on its own function host. Re-issue the admin cookie explicitly on the public Render host before redirecting.
s=s.replace("if(up.status>=300&&up.status<400&&up.headers.get('location'))return res.redirect(303,up.headers.get('location'));","if(up.status>=300&&up.status<400&&up.headers.get('location')){let loc=up.headers.get('location'),sc=up.headers.get('set-cookie');if(sc){let m=sc.match(/tc_admin=([^;]+)/);if(m)res.cookie('tc_admin',decodeURIComponent(m[1]),{httpOnly:true,secure:true,sameSite:'lax',maxAge:28800000,path:'/'});}return res.redirect(303,loc)}");
// Keep receipt/order card opaque.
s=s.replace("if(t.includes('text/html')||p.startsWith('/admin')||p.startsWith('/order/'))return res.status(up.status).type('html').send(await deco(await up.text(),p));","if((t.includes('text/html')||p.startsWith('/admin')||p.startsWith('/order/'))&&!p.startsWith('/admin/receipt/')){let html=await deco(await up.text(),p);if(p.startsWith('/order/'))html=html.replace(/<body([^>]*)>/i,'<body$1><div class=orderopaque>').replace('</body>','</div></body>');return res.status(up.status).type('html').send(html)}");
// Preserve PDF/image headers and bytes for private admin receipts instead of coercing them to HTML.
s=s.replace("res.status(up.status).end(Buffer.from(await up.arrayBuffer()))","if(p.startsWith('/admin/receipt/')){for(let [k,v] of up.headers)if(!['content-length','transfer-encoding','connection'].includes(k.toLowerCase()))res.setHeader(k,v)}res.status(up.status).end(Buffer.from(await up.arrayBuffer()))");
s=s.replaceAll("v=38","v=51").replace("service:'tuconis-v38'","service:'tuconis-v51'");
writeFileSync(new URL('./proxy-runtime-v51.js',import.meta.url),s);
await import('./proxy-runtime-v51.js');
