import{readFileSync,writeFileSync}from'node:fs';
let s=readFileSync(new URL('./proxy-v34.js',import.meta.url),'utf8');
const cartStart=s.indexOf('const cart=`');
const cartEnd=s.indexOf('`;const shell=',cartStart);
if(cartStart<0||cartEnd<0)throw new Error('cart template not found');
// v42: simple parse-safe cart. All actions use data attributes + one delegated click handler.
const cart=`const cart=\`<button class=cartbtn type=button data-cart-toggle>🛒 Carrito <span id=tcN>0</span></button><aside class=drawer id=tcD><b>Tu carrito</b><div id=tcItems></div><div id=tcPrice style="padding:12px 0;font-weight:900"></div><a class=btn href=/checkout>Ir al checkout →</a></aside><script>var TCK='tuconis-cart-v1',TCN={black:'GRIS / NEGRA',red:'ROJA / BORDÓ',blue:'AZUL'};function tcGet(){try{return JSON.parse(localStorage.getItem(TCK)||'{}')}catch(e){return{}}}function tcSave(c){localStorage.setItem(TCK,JSON.stringify(c));tcRender()}function tcQty(){return Object.values(tcGet()).reduce(function(a,b){return a+Number(b||0)},0)}function tcPrice(n){return Math.floor(n/2)*50000+(n%2)*30000}function tcRender(){var c=tcGet(),n=tcQty(),el=document.getElementById('tcN');if(el)el.textContent=n;var x=document.getElementById('tcItems');if(x){var rows=Object.entries(c).filter(function(kv){return Number(kv[1])>0}).map(function(kv){var k=kv[0],v=kv[1];return '<div class="cartrow"><span>'+TCN[k]+'</span><span class="ctrl"><button type="button" data-cart-change="-1" data-model="'+k+'">−</button><b>'+v+'</b><button type="button" data-cart-change="1" data-model="'+k+'">+</button></span></div>'}).join('');x.innerHTML=rows||'<p>Tu carrito está vacío.</p>'}var p=document.getElementById('tcPrice');if(p)p.textContent=n?'Total estimado por transferencia: $'+tcPrice(n).toLocaleString('es-AR'):''}function tcChg(k,d){var c=tcGet();c[k]=Math.max(0,Number(c[k]||0)+Number(d));tcSave(c);if(typeof syncCheckout==='function')syncCheckout()}function tcAdd(k,n){n=n||1;var c=tcGet();c[k]=Number(c[k]||0)+n;tcSave(c);var d=document.getElementById('tcD');if(d)d.classList.add('open')}function tcToggle(){var d=document.getElementById('tcD');if(d)d.classList.toggle('open')}document.addEventListener('DOMContentLoaded',function(){tcRender();document.addEventListener('click',function(e){var add=e.target.closest('[data-add-cart]');if(add){e.preventDefault();tcAdd(add.getAttribute('data-model'),1);return}var ch=e.target.closest('[data-cart-change]');if(ch){e.preventDefault();tcChg(ch.getAttribute('data-model'),Number(ch.getAttribute('data-cart-change')));return}var tog=e.target.closest('[data-cart-toggle]');if(tog){e.preventDefault();tcToggle()}})});</script>\``;
s=s.slice(0,cartStart)+cart+s.slice(cartEnd+1);
s=s.replace(".adminlegacy{display:none!important}",".adminlegacy{display:none!important}.socialfooter{position:relative;z-index:2;text-align:center;padding:34px 12px 26px;font-family:Arial,sans-serif;font-size:14px;font-weight:600;letter-spacing:.4px}.socialfooter a{color:#eee8df;text-decoration:none;margin:0 12px;border-bottom:1px solid #ef3030;padding-bottom:3px}.socialfooter a:hover{color:#ef3030}");
s=s.replace("${cards()}</main>`))});app.get('/promo'","${cards()}</main><footer class=socialfooter><a href=\"https://www.instagram.com/tuconis/\" target=\"_blank\" rel=\"noopener\">Instagram · @tuconis</a><a href=\"https://www.youtube.com/@Tuconis\" target=\"_blank\" rel=\"noopener\">YouTube · @Tuconis</a></footer>`))});app.get('/promo'");
// Product buttons use the same delegated handler as the cart.
s=s.replaceAll("<button class=btn onclick=\"tcAdd('${id}')\">Agregar al carrito</button>","<button type=button class=btn data-add-cart data-model=\"${id}\">Agregar al carrito</button>");
// Pricing and checkout copy.
s=s.replace("<div class=price>1 GORRA · $30.000</div>","<a class=price href=/checkout>1 GORRA<br><small>TRANSFERENCIA · $30.000</small><br><small>MERCADO PAGO (DÉBITO / CRÉDITO) · $32.500</small><br><small>Ir al checkout →</small></a>");
s=s.replace("2 GORRAS · $50.000<br><small>Elegí cualquier combinación →</small>","2 GORRAS · $50.000<br><small>SOLO TRANSFERENCIA · hasta agotar 5 pares<br>Elegí cualquier combinación →</small>");
s=s.replace("Podés combinar colores o elegir dos iguales. La promo se suma a lo que ya tengas en el carrito.","Podés combinar colores o elegir dos iguales. Promoción exclusiva por transferencia directa. No disponible con débito ni crédito.");
s=s.replace("<div class=pay><b>Forma de pago</b>","<div class=pay><b>Forma de pago</b><p><small>Transferencia: $30.000 por gorra; promo 2 × $50.000 mientras haya cupo. Mercado Pago (débito/crédito): $32.500 por gorra, sin promoción.</small></p>");
s=s.replace("Mientras haya cupo promocional, cada par se cobra $50.000 y las unidades restantes $30.000 c/u. El servidor confirma el precio final al crear el pedido.","Por transferencia, mientras haya cupo promocional, cada par se cobra $50.000 y las unidades restantes $30.000 c/u. Con Mercado Pago cada gorra cuesta $32.500 y la promoción no se aplica. El servidor confirma el total final.");
s=s.replaceAll("v=38","v=42").replace("service:'tuconis-v38'","service:'tuconis-v42'");
writeFileSync(new URL('./proxy-runtime-v42.js',import.meta.url),s);
await import('./proxy-runtime-v42.js');
